version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  tournoi_server:
    container_name: 'tournoi_server'
    build: .
    volumes:
      - '.:/var/www/html'
      - '/var/www/html/vendor'
    ports:
      - "6666:80"
    depends_on:
      - tournoi_db
    networks:
      - app-network
    restart: always

  tournoi_db:
    image: postgis/postgis:11-2.5
    container_name: 'tournoi_db'
    restart: always
    ports:
      - "54326:5432"
    environment:
      POSTGRES_PASSWORD: tournoi
    networks:
      - app-network

  postgresadmin:
    image: dpage/pgadmin4
    container_name: 'tournoipostgresadmin'
    restart: always
    ports:
      - "6060:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tournoi.ma
      PGADMIN_DEFAULT_PASSWORD: tournoi
    depends_on:
      - tournoi_db
    networks:
      - app-network

